[package]
authors = ["winger <isenbaev@gmail.com>"]
name = "cargo-metadata"
version = "0.1.0"

[[bin]]
doc = true
name = "cargo-metadata"
test = false

[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo.git" }
docopt = "0.6.76"
rustc-serialize = "0.3.16"
toml = "0.1.23"
